### ISSUE TITLE
Location errors

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#21]
location data out of range for lat, lon, elevation, mat, mat.
no idea what's going on here, but I'm going to try moving on, as data seem OK?
https://drive.google.com/open?id=1J-9jO2eU4QmmtOKr94_AHe6Q6g3ZrXwj

**Comment by piersond** [comment]
Guessing this is a bug from the unit conversion changes Stevan started on yesterday. Looks like everything in that keykey location tab with a unit came back with a QC error.

**Comment by srearl** [comment]
I think this was related to the files detailing acceptable QC ranges being corrupted. Closing this issue for now but revisit if the issue surfaces again.
