### ISSUE TITLE
numeric flags

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#22]
not sure why not all numeric fields are not expected to be numeric.  just homog'ed site where 15N and 13C were read in as characters (I think because they had NA in the column).  Replacing 'NA' with '.' fixed the issue, but it made me wonder if other characters are getting added into the homog'ed files.

**Comment by srearl** [comment]
@wwieder which data set were you working with here, that will help me troubleshoot?

**Comment by wwieder** [comment]
This was on the SWaN data from Harvard Forest.  NA was defined as an NA in the key-key file and missing values used NA in the raw data and seemed to make the column read in as character.  I only noticed because the notes threw an error for total soil C and N, but other numeric fields also were being read in as characters (without the error).  

This data is fine, now, but are there other homogenized data sets where this may have occurred?  Is it something we can check on making the tarball?

**Comment by srearl** [comment]
I think this was related to the files detailing acceptable QC ranges being corrupted. Closing this issue for now but revisit if the issue surfaces again.
