### ISSUE TITLE
QC max-min values in different units from homog data values

### ISSUE THREAD

**Issue by piersond** [srearl/soilHarmonization#24]
Looking at UMBS DIRT, the above ground biomass (agb) value is 16400 g/m2, which returned a QC flag as above the max value. The max value in the data/locationQC.rda is 40 kg/m2. As this equates to 40000 g/m2, and no flag should have been raised, I'm guessing we need to either add a program step to run a unit conversion on the existing QC min-max values or manually update them.

**Comment by srearl** [comment]
did we address this with #23 or do we need to consider this separately?

**Comment by wwieder** [comment]
seem to be resolved with #23. I'll with some other sites before too long.
