### ISSUE TITLE
publishing NOTES?

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#30]
I'm starting to think about publishing our database and am struck by the amount of data that's potentially useful in the NOTES.  For example, users should sum 'replicates' of NEON litterfall data for each 'block' as these are the functional litter types (leaves, needles, etc) that are measured in each trap.  There are also information about units & their conversion, as well as user provide comments that may be helpful in analyses.  How to we handle these kinds of 'meta data'?  This is only a github issue, @srearl if we want to think about pulling down the notes files when we generate the tarball?

**Comment by srearl** [comment]
You are referring to the notes in the post-homogenization PDF, right? If so, yeah, I agree, that is a lot of information. What about linking to the notes PDF for each dataset from the tarball and/or the shiny app sensu as we had done for the QC plots we generated in the first round?

**Comment by wwieder** [comment]
That's right.  in the first round we put the qc plots up on the website.  Maybe that's the best thing to do with the note? Linking them to the shiny app could also be nice what's involved with that @piersond?

**Comment by piersond** [comment]
I love the idea of getting that QC information up on the Shiny app! A simple approach would be to add a QC tab that gives a big list of links to the PDFs, I don't see that code being a huge lift. Is there another way/page/table you'd like to see this implemented?  

Adding this as a issue on the Shiny app repo.
