### ISSUE TITLE
tarball flags

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#34]
@derek suggested we generate column in the tarball to identify control samples easily.  This can be done by [modifying this code ](https://github.com/lter/lterwg-som/blob/master/data-processing/Tarball_v2%20scripts/Filter/Control%20data%20only/SOM_control_data_filter.R)while the tarball is being generated.

**Comment by srearl** [comment]
sibling of: https://github.com/lter/lterwg-som/issues/68

**Comment by srearl** [comment]
now added to tarball processing script; though not certain, it appears that only NWT snow fence data has a combination of vars to denote control samples, script is operating under this assumption.

[som_multiple_control_ids.txt](https://github.com/srearl/soilHarmonization/files/3769768/som_multiple_control_ids.txt)
