### ISSUE TITLE
are dependencies being loaded?

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#5]
trying to run QA function again, which fails because 'rmarkdown' was not installed.

This is easy enough to correct, but should dependencies load when users load soilHarmonization?

**Comment by srearl** [comment]
@wwieder that is odd, do you mean it ran smoothly a first time but when you went to run it once more it did not? Have to think about that if so. I think Rmarkdown is automatically installed with Rstudio, assuming most folks are using that, but it would probably be prudent to make Rmarkdown a dependency explicitly.

**Comment by srearl** [comment]
added rmarkdown import to Roxygen
