### ISSUE TITLE
view html from QA function

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#6]
How do I view the html file generated by the QA function?  The file is created and uploaded in BNZ3, but I can't seem to open it (from Google Drive using a mac). 

I'm fine maintaining this approach, if there's an easy way we can point data providers to the plots.  Otherwise, does it make more sense to generate a pdf or some other file type?

**Comment by srearl** [comment]
Thanks @wwieder issues welcome. This actually is documented in the README but is kinda' buried, I should probably call more attention to it. Google Drive sees the html file as a text file, so you need to download it and open it with a browser (or the most recent one will be in your working directory so you can open it at that location).

```Script output is a single html file with a file name generated from the temporaryDirectory and directoryName, and appended with "_HMGZD_QC.html". Please note that html files do not render properly if opended in Google Drive, so the file should be downloaded and opened using a web browser, or viewed from the temporaryDirectory where a copy of the file will also reside.```

**Comment by wwieder** [comment]
a thanks Stevan. maybe this should be marked as resolved.
